//
// Created by mpl on 23-12-25.
//

#ifndef CANNYEVIT_INCLUDE_EIGENOPTIMIZATION_PROBLEM_SLIDINGWINDOWPROBLEM_H_
#define CANNYEVIT_INCLUDE_EIGENOPTIMIZATION_PROBLEM_SLIDINGWINDOWPROBLEM_H_

#endif //CANNYEVIT_INCLUDE_EIGENOPTIMIZATION_PROBLEM_SLIDINGWINDOWPROBLEM_H_
